apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: payment
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./module/helm/application
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  releaseName: payment
  values: {}