apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - services.yaml
  - hpa.yaml
  # - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: env
    files:
      - .env